import Head from "next/head";
import styles from "../styles/Home.module.css";

import React, { useState, useEffect } from "react";
import getBlockchain from "../ethereum";

export default function Home() {
  const [simpleStorage, setSimpleStorage] = useState(undefined);
  const [data, setData] = useState(undefined);

  useEffect(() => {
    const init = async () => {
      const { simpleStorage } = await getBlockchain();
      const data = await simpleStorage.readData();
      setSimpleStorage(simpleStorage);
      setData(data);
    };
    init();
  }, []);

  const updateData = async (e) => {
    e.preventDefault();
    const data = e.target.elements[0].value;
    const tx = await simpleStorage.updateData(data);
    await tx.wait();
    const newData = await simpleStorage.readData();
    setData(newData);
  };

  if (typeof simpleStorage === "undefined" || typeof data === "undefined") {
    return "Loading...";
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Hello there from Solidity :) */}

      
        <div>
          <h2>Data:</h2>
          <p>{data.toString()}</p>
        </div>

        <div>
          <h2>Change data</h2>
          <form  onSubmit={(e) => updateData(e)}>
            <input type="text"  placeholder="data" />
            <button type="submit">
              Submit
            </button>
          </form>
        </div>
      </div>
    </div>
  );
}
